name: Update US Wastewater data (conversion factor approach)

on: #yamllint disable-line rule:truthy  
  push:
    branches: [main]
  schedule:
    - cron: '05 20 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Process Data
      run: |
        python ww_factor_NWSS.py
        python ww_factor_NWSS_min.py
        python ww_variants_CDC.py
        python Joe_variant_infections.py
        python Joe_variant_infections_min.py
        #python ww_factor_US_states.py
        #python ww_factor_US.py

    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit --all --allow-empty -m "Auto-update of the data packages"
        git pull --rebase=false

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
